# Generated by Django 5.0.4 on 2024-05-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0003_alter_ingredient_unit_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media'),
        ),
    ]
