# Generated by Django 5.0.4 on 2024-05-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0005_recipe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
    ]
