# Generated by Django 5.0.4 on 2024-05-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0006_remove_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('italian', 'Italian'), ('indian', 'Indian'), ('mexican', 'Mexican'), ('chinese', 'Chinese'), ('mediterranean', 'Mediterranean'), ('japanese', 'Japanese'), ('thai', 'Thai'), ('french', 'French'), ('american', 'American'), ('greek', 'Greek'), ('asian', 'Asian')], default=None, max_length=32, null=True),
        ),
    ]
