# Generated by Django 5.0.4 on 2024-05-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0008_recipe_date_alter_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.CharField(blank=True, choices=[('15-20 mins', '15-20 mins'), ('20-45 mins', '20-45 mins'), ('45 mins to 1 hr', '45 mins to 1 hr'), ('1 hr+', '1 hr+')], default=None, max_length=32, null=True),
        ),
    ]
