# Generated by Django 5.0.4 on 2024-05-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0009_recipe_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('chef', 'Chef')], default=None, max_length=32, null=True),
        ),
    ]
