# Generated by Django 5.0.4 on 2024-05-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cost',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('mg', 'milligrams'), ('lb', 'pounds'), ('oz', 'ounces'), ('ml', 'milliliters'), ('l', 'liters'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('cup', 'cups'), ('pt', 'pints'), ('qt', 'quarts'), ('slices', 'slices'), ('sticks', 'sticks')], default=None, max_length=32),
        ),
    ]
