# Generated by Django 5.0.4 on 2024-05-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0014_profile_bio_recipe_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media'),
        ),
    ]
