# Generated by Django 5.0.4 on 2024-05-27 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0017_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_profiles', to='foodhub.recipe'),
        ),
    ]
