# Generated by Django 5.0.4 on 2024-06-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0018_profile_featured_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('mg', 'milligrams'), ('lb', 'pounds'), ('oz', 'ounces'), ('ml', 'milliliters'), ('l', 'liters'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('cup', 'cups'), ('pt', 'pints'), ('qt', 'quarts'), ('slices', 'slices'), ('sticks', 'sticks'), ('scoops', 'scoops'), ('none', 'none')], default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('american', 'American'), ('appetizer', 'Appetizer'), ('asian', 'Asian'), ('beverage', 'Beverage'), ('brunch', 'Brunch'), ('breakfast', 'Breakfast'), ('chinese', 'Chinese'), ('cocktail', 'Cocktail'), ('dessert', 'Dessert'), ('dinner', 'Dinner'), ('filipino', 'Filipino'), ('french', 'French'), ('gluten-free', 'Gluten-Free'), ('greek', 'Greek'), ('indian', 'Indian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('lunch', 'Lunch'), ('mediterranean', 'Mediterranean'), ('mexican', 'Mexican'), ('pastry', 'Pastry'), ('pasta', 'Pasta'), ('pizza', 'Pizza'), ('salad', 'Salad'), ('sandwiches', 'Sandwiches'), ('seafood', 'Seafood'), ('snack', 'Snack'), ('soup', 'Soup'), ('steak', 'Steak'), ('thai', 'Thai'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian')], default=None, max_length=32, null=True),
        ),
    ]
