# Generated by Django 5.0.4 on 2024-06-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0019_step_image_alter_ingredient_unit_of_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
