# Generated by Django 5.0.4 on 2024-06-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0020_alter_step_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='image',
        ),
    ]
