# Generated by Django 5.0.4 on 2024-06-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0021_remove_step_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
