# Generated by Django 5.0.4 on 2024-06-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0022_step_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
