# Generated by Django 5.0.4 on 2024-06-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0024_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
