# Generated by Django 5.0.4 on 2024-06-13 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0026_profile_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('recipes', models.ManyToManyField(to='foodhub.recipe')),
            ],
        ),
    ]
