# Generated by Django 5.0.4 on 2024-06-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0031_profile_favorite_cuisines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_cuisines',
            field=models.ManyToManyField(blank=True, related_name='favorite_cuisines', to='foodhub.recipe'),
        ),
    ]
