# Generated by Django 5.0.4 on 2024-06-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0033_remove_profile_favorite_cuisines'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_cuisines',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_profiles', to='foodhub.recipe'),
        ),
    ]
